### PR TITLE
Update icc/icx CXX flags

### PR DESCRIPTION
**Pull request by jfowkes**
@nimgould the CXX flag updates to icc/icx that you requested

### CODE REVIEW

**Review by nimgould — COMMENTED** [review]
We don't need the -diag-disable=10441 flag for the icx ones, as this only says that icc is on its way out

**Comment by jfowkes** [comment]
Ah yes, only just looked up what that means, will remove it now. 

Btw it should be possible to mix icx and ifort when they do remove icc if ifx is not up to scratch by that point.

**Review by nimgould — APPROVED** [review]
Perfect

**Comment by dpo** [comment]
Why add a standard include path to the arguments?

**Comment by nimgould** [comment]
if you mean /usr/local/include, simply as it didn't appear on the path on my linux

**Comment by nimgould** [comment]
Damnation ... the -fopenmp  gets rid of the unrecognized OpenMP #pragma
                 #pragma omp task
messages, but then the link step complains about a bunch of undefined reference to omp_* and komp_* . So I'm afraid that we should remove these changes. Pah!

**Comment by jfowkes** [comment]
I think you need to also link with OpenMP

**Comment by nimgould** [comment]
Yes, you are right. I'll have to change the link flags accordingly ... tomorrow

**Comment by nimgould** [comment]
OPENMP = -fopenmp and SOMP = -fopenmp does the job. Thanks

**Pull request merged**
