### PR TITLE
Add -Wl for LOADALL and LOADNONE variables

### PR DESCRIPTION
**Pull request by amontoison**
@nimgould

### CODE REVIEW

**Review by nimgould — APPROVED** [review]
Perfecto! Don't you ever sleep?

**Comment by amontoison** [comment]
> Perfecto! Don't you ever sleep?

I wake up very late yesterday, I probably drank too much tea(quila) saturday night :)

**Comment by nimgould** [comment]
My sympathies! I stick to beer and wine nowadays

**Comment by nimgould** [comment]
Ooops, just noticed that the NOUNDEFINED are missing after the latest change

**Comment by amontoison** [comment]
> Ooops, just noticed that the NOUNDEFINED are missing after the latest change

You didn't merge the PR #24 for the `NOUNDEFINED` variable.

**Comment by nimgould** [comment]
That option is no longer there for #24 for me, so I can't see the changes. I get a merging is blocked message. Help

**Pull request merged**
